# Generated by Django 2.1.1 on 2018-10-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('query',),
            },
        ),
    ]
